# Generated by Django 5.0.7 on 2024-07-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_field_of_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
